---
- name: install python3 pip
  apt:
    name: 
    - python3-pip
    - python3-mysqldb
    state: latest
    update_cache: true

- name: install flask
  pip:
    name:
    - flask
    - flask-mysql
    - uwsgi