---
- name: install python3 pip
  apt:
    name: 
    - python3-pip
    - python3-mysqldb
    state: latest
    update_cache: true

- name: Install Flask and MySQL dependencies
  pip:
    name:
      - flask
      - mysql-connector-python
      - flask-mysql

