---
- name: install galera pkgs
  dnf:
    name: 
    - mariadb-server-galera.x86_64
    - galera
    - rsync
    - policycoreutils-python-utils.noarch
    state: present

- name: Allow galera Ports
  firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    permanent: true
  loop:
    - 4444/tcp
    - 4567/tcp
    - 4568/tcp
    - 4568/udp
    - 4567/udp
  notify:
  - firewalld_reload

- meta: flush_handlers

- name: Allow source
  firewalld:
    zone: public
    source: "{{item}}"
    state: enabled
    permanent: true
  loop:
  - "{{ip_1}}/32"
  - "{{ip_2}}/32"
  - "{{ip_3}}/32"

- meta: flush_handlers


- name: push file to servers
  template:
    src: galera.cnf.j2
    dest: /etc/my.cnf.d/galera.cnf

# sudo nano /var/lib/mysql/grastate.dat 
- name: Update safe_to_bootstrap value using lineinfile
  lineinfile:
    path: /var/lib/mysql/grastate.dat
    regexp: '^safe_to_bootstrap: 0$'
    line: 'safe_to_bootstrap: 1'

- name: new cluster
  command: galera_new_cluster
  when: ansible_host == ip_1

- name: start maria
  systemd:
    name: mariadb
    state: started

