---
- name: add hostname 
  lineinfile:
    path: /etc/hosts
    line:  "{{ ip_1 }} db1.mydomain.org"

- name: Copy service files
  copy:
    src: app.service
    dest: /etc/systemd/system/
  # notify:
  #   - add_db_to_hosts

- name: enable_service
  command: systemctl enable app.service

- meta: flush_handlers

- name: Copy nginx file  
  copy:
    src: app.conf
    dest: /etc/nginx/sites-available/default
  notify:
  - sites-enabled
  - restart_nginx

- meta: flush_handlers 

- name: start_service
  command: systemctl restart app.service